output "id" {
  description = "Autogenerated ID of the Resource, encoded in base64"
  value       = twingate_resource.this.id
}

output "tags_all" {
  description = "A map of key-value pairs that represents all tags on this resource, including default tags from provider configuration"
  value       = twingate_resource.this.tags_all
}
